In [1]:
import torch
from triton.language import tensor

print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print('GPU available')
    print(f'using GPU: {torch.cuda.get_device_name(torch.cuda.current_device())}')
else:
    print('GPU not available')

GPU available
using GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU


# Creating a Tensor

In [7]:
a =torch.empty(2,3)

In [8]:
type(a)

torch.Tensor

In [9]:
print(a)

tensor([[3.6437e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4082e-39]])


In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.manual_seed(23)
b =torch.rand(2,3)

In [16]:
torch.manual_seed(23)
c =torch.rand(2,3)

In [20]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [23]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [24]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [28]:
torch.full((4,3),2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## Tensor Shape

In [29]:
x = a.shape

In [30]:
print(x)

torch.Size([2, 3])


In [34]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [44]:
torch.rand_like(a, dtype=torch.float).to(torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [43]:
p = torch.ones(2,2, dtype=torch.float)