In [3]:
import torch
from sklearn.datasets import make_classification

In [4]:
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [10]:
batch_size =32
epochs =25
n_samples = len(X)

for epoch in range(epochs):
    for start_idx in range(0,n_samples-batch_size,batch_size):
        end_idx = batch_size+ start_idx


In [5]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [6]:
from torch.utils.data import Dataset, DataLoader

In [7]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [8]:
data = CustomDataset(X,y)

In [9]:
dataLoader = DataLoader(data, batch_size=batch_size, shuffle=True)

In [11]:
type(DataLoader)

type

In [12]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [13]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [14]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [15]:
data.__len__()

10

In [16]:
data.__getitem__(0)

(tensor([ 1.0683, -0.9701]), tensor(1))