In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out



In [3]:
features = torch.rand(10,5)

In [4]:
model = Model(features.shape[1])

In [5]:
pred = model(features)

In [6]:
pred

tensor([[0.5235],
        [0.5025],
        [0.5629],
        [0.5024],
        [0.4614],
        [0.4629],
        [0.5291],
        [0.4906],
        [0.4786],
        [0.5320]], grad_fn=<SigmoidBackward0>)

In [7]:
pred = (pred > 0.5).float()

In [8]:
pred

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])

In [9]:
from torchinfo import  summary

In [10]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [11]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.rulu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.rulu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [12]:
torch.manual_seed(43)
features = torch.rand(10, 5)
model = Model(features.shape[1])

In [13]:
pred = model(features)

In [14]:
pred

tensor([[0.5930],
        [0.6086],
        [0.5950],
        [0.6024],
        [0.6059],
        [0.6021],
        [0.6013],
        [0.6043],
        [0.6016],
        [0.6011]], grad_fn=<SigmoidBackward0>)

In [15]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Sequential Container

In [16]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.cont = nn.Sequential(nn.Linear(num_features, 3),
                                  nn.ReLU(),
                                  nn.Linear(3, 1),
                                  nn.Sigmoid())

    def forward(self, x):
        out = self.cont(x)
        return out

In [17]:
torch.manual_seed(43)
features = torch.rand(10, 5)
model = Model(features.shape[1])

In [18]:
pred = model(features)

In [19]:
pred

tensor([[0.5930],
        [0.6086],
        [0.5950],
        [0.6024],
        [0.6059],
        [0.6021],
        [0.6013],
        [0.6043],
        [0.6016],
        [0.6011]], grad_fn=<SigmoidBackward0>)