In [1]:
import torch
from triton.language import tensor

print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print('GPU available')
    print(f'using GPU: {torch.cuda.get_device_name(torch.cuda.current_device())}')
else:
    print('GPU not available')

GPU available
using GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU


# Creating a Tensor

In [7]:
a =torch.empty(2,3)

In [8]:
type(a)

torch.Tensor

In [9]:
print(a)

tensor([[3.6437e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4082e-39]])


In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.manual_seed(23)
b =torch.rand(2,3)

In [16]:
torch.manual_seed(23)
c =torch.rand(2,3)

In [20]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [23]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [24]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [28]:
torch.full((4,3),2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## Tensor Shape

In [29]:
x = a.shape

In [30]:
print(x)

torch.Size([2, 3])


In [34]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [35]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [44]:
torch.rand_like(a, dtype=torch.float).to(torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [43]:
p = torch.ones(2,2, dtype=torch.float)

In [45]:
a+b

tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])

In [48]:
a+2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [49]:
a-2

tensor([[-2., -2., -2.],
        [-2., -2., -2.]])

In [51]:
a+2*100//2

tensor([[100., 100., 100.],
        [100., 100., 100.]])

In [52]:
a*b

tensor([[1.5605e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.8469e-40]])

In [53]:
a/b

tensor([[8.5082e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.0091e-38]])

In [54]:
a**b

tensor([[3.3857e-05, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.0626e-05]])

In [55]:
a % b

tensor([[3.6437e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4082e-39]])

In [56]:
torch.abs(c)

tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])

In [57]:
torch.neg(c)

tensor([[-0.4283, -0.2889, -0.4224],
        [-0.3571, -0.9577, -0.1100]])

In [58]:
torch.round(c)

tensor([[0., 0., 0.],
        [0., 1., 0.]])

In [59]:
torch.ceil(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [60]:
torch.floor(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [65]:
torch.clamp(a , min=0,max=1)

tensor([[3.6437e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4082e-39]])

## Tensor Reduction

In [66]:
e = torch.randint(size=(2,3), low =2 , high =10)

In [67]:
e

tensor([[8, 3, 5],
        [3, 5, 9]])

In [68]:
e.sum()

tensor(33)

In [72]:
e.sum(dim=0)

tensor([11,  8, 14])

In [73]:
e.sum(dim=1, keepdim=True)

tensor([[16],
        [17]])

In [77]:
e.mean(dim=0)
e.mean(dim=1, keepdim=True)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [79]:
K =e.to(torch.float)

In [80]:
K.mean(dim=0)
K.mean(dim=1, keepdim=True)

tensor([[5.3333],
        [5.6667]])

In [82]:
K.median(dim=0)

torch.return_types.median(
values=tensor([3., 3., 5.]),
indices=tensor([1, 0, 0]))

In [83]:
K.max()

tensor(9.)

In [85]:
K.amax()

tensor(9.)

## Tensor Operation

In [ ]:
 # transpose

In [ ]:
# torch.dot

In [ ]:
# torch.det

In [ ]:
# torch.inverse

In [ ]:
# torch.cross

## Comparison Operator

In [88]:
i = torch.randint(size=(2,3), low =2 , high =10)
j= torch.randint(size=(2,3), low =2 , high =10)

In [90]:
torch.greater(i, j)

tensor([[False, False, False],
        [False, False,  True]])

In [91]:
torch.equal(i, j)

False

In [92]:
torch.not_equal(i, j)

tensor([[False,  True,  True],
        [ True, False,  True]])

In [93]:
torch.greater_equal(i,j)

tensor([[ True, False, False],
        [False,  True,  True]])

## Special Function

In [95]:
# sigmoid

In [96]:
# Softmax

In [97]:
# sqrt

In [98]:
# relu

## Inplace Operation

In [100]:
i = torch.randint(size=(2,3), low =2 , high =10)
j= torch.randint(size=(2,3), low =2 , high =10)

In [101]:
i.add_(j)

tensor([[13,  5,  6],
        [11, 12, 15]])

In [102]:
i

tensor([[13,  5,  6],
        [11, 12, 15]])

In [103]:
torch.add(i,j,out=i)

tensor([[18,  7,  8],
        [18, 18, 23]])

In [104]:
i

tensor([[18,  7,  8],
        [18, 18, 23]])

In [111]:
torch.relu_(i )
i.sub_(10)

tensor([[  3, -10, -10],
        [  5,   4,  11]])

In [112]:
torch.relu_(i )

tensor([[ 3,  0,  0],
        [ 5,  4, 11]])

## Tensor Operation on GPU

In [117]:
torch.cuda.is_available()

True

In [119]:
device = torch.device('cuda')

In [120]:
device

device(type='cuda')

In [121]:
i = torch.rand(size=(10,10), device=torch.device('cuda'))

In [122]:
i

tensor([[0.3186, 0.6480, 0.0896, 0.6143, 0.8915, 0.9506, 0.1050, 0.1112, 0.6743,
         0.6665],
        [0.9905, 0.4364, 0.2021, 0.5753, 0.4452, 0.7684, 0.0118, 0.1458, 0.5906,
         0.3770],
        [0.6148, 0.6595, 0.6404, 0.7487, 0.2047, 0.4303, 0.1577, 0.0268, 0.3150,
         0.8701],
        [0.0042, 0.1301, 0.0285, 0.6652, 0.4209, 0.3953, 0.5955, 0.2224, 0.3663,
         0.6285],
        [0.6030, 0.5292, 0.1678, 0.3133, 0.1680, 0.2362, 0.6739, 0.6119, 0.4848,
         0.3609],
        [0.0281, 0.5881, 0.1775, 0.8234, 0.9582, 0.1134, 0.0897, 0.2174, 0.2125,
         0.3243],
        [0.3647, 0.4997, 0.4781, 0.2818, 0.4677, 0.2420, 0.7875, 0.7843, 0.7740,
         0.6381],
        [0.3196, 0.1148, 0.5723, 0.4967, 0.9201, 0.7533, 0.5857, 0.9993, 0.9942,
         0.6669],
        [0.8300, 0.7043, 0.3365, 0.2523, 0.7880, 0.0184, 0.0932, 0.5202, 0.3756,
         0.2580],
        [0.5118, 0.1915, 0.0202, 0.4407, 0.8791, 0.1150, 0.8012, 0.3497, 0.4674,
         0.3692]], device='c

In [123]:
import  time

In [124]:
%time
torch.rand(size=(10,10), device=torch.device('cuda'))


CPU times: user 4 μs, sys: 0 ns, total: 4 μs
Wall time: 10.3 μs


tensor([[3.8089e-01, 1.3049e-01, 3.8601e-01, 1.3550e-01, 4.9882e-01, 9.8652e-01,
         3.9582e-01, 8.5642e-01, 4.5206e-01, 8.0657e-02],
        [4.8784e-01, 9.7273e-02, 9.0704e-01, 5.0520e-01, 7.2740e-01, 5.6856e-01,
         2.0249e-01, 6.2343e-01, 6.4696e-01, 5.1150e-01],
        [6.4464e-01, 6.4426e-01, 1.9410e-01, 6.0345e-01, 7.5366e-01, 8.1003e-01,
         4.9509e-01, 2.4470e-01, 2.0779e-01, 9.6912e-01],
        [5.6745e-01, 9.8288e-01, 6.2176e-01, 5.1386e-02, 5.8969e-01, 7.5345e-01,
         9.1446e-01, 9.0366e-02, 3.4811e-01, 2.7145e-01],
        [4.5456e-01, 9.6167e-01, 7.1631e-01, 6.8086e-01, 6.5048e-01, 9.8384e-01,
         1.5791e-01, 2.2719e-01, 2.0854e-01, 1.2164e-01],
        [7.7737e-01, 6.2015e-01, 6.8831e-01, 8.4722e-01, 5.4024e-01, 6.3643e-01,
         9.1965e-01, 8.9724e-01, 1.4207e-01, 7.6336e-01],
        [4.3387e-01, 6.0528e-01, 9.8823e-02, 7.3699e-02, 1.4112e-01, 5.6666e-01,
         1.5324e-01, 2.9212e-01, 4.0456e-01, 4.3445e-01],
        [9.6227e-01, 2.1047

In [125]:
%time
torch.rand(size=(10,10))

CPU times: user 1 μs, sys: 0 ns, total: 1 μs
Wall time: 3.81 μs


tensor([[0.1604, 0.4215, 0.7701, 0.4345, 0.5220, 0.6480, 0.6743, 0.1183, 0.2176,
         0.7503],
        [0.8487, 0.3463, 0.7885, 0.6293, 0.8827, 0.7106, 0.4752, 0.8855, 0.2817,
         0.4441],
        [0.6524, 0.7804, 0.0450, 0.4816, 0.8964, 0.9583, 0.7729, 0.7437, 0.6313,
         0.1613],
        [0.5894, 0.3005, 0.5500, 0.1084, 0.5669, 0.4223, 0.6621, 0.1252, 0.6694,
         0.6640],
        [0.8102, 0.8767, 0.4744, 0.3245, 0.0996, 0.4268, 0.8953, 0.9632, 0.3493,
         0.5842],
        [0.2382, 0.4284, 0.2353, 0.3347, 0.0178, 0.5721, 0.7608, 0.6129, 0.2003,
         0.7282],
        [0.9941, 0.9900, 0.0403, 0.3992, 0.6004, 0.5971, 0.1082, 0.7593, 0.6926,
         0.6031],
        [0.6065, 0.8346, 0.3135, 0.2728, 0.2653, 0.9789, 0.9646, 0.6824, 0.2790,
         0.7209],
        [0.8624, 0.2009, 0.1143, 0.2200, 0.3224, 0.3837, 0.0489, 0.2061, 0.9507,
         0.5270],
        [0.4491, 0.2293, 0.3698, 0.5259, 0.6364, 0.7610, 0.4425, 0.1400, 0.8017,
         0.1875]])

### lets go test

In [127]:
size = 10000

In [128]:
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

start_time = time.time()
matrix_cpu3 = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(cpu_time)

matrix_gpu1 = torch.rand(size,size, device=torch.device('cuda'))
matrix_gpu2 = torch.rand(size,size, device=torch.device('cuda'))

start_time = time.time()
matrix_gpu3 = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(gpu_time)

print(cpu_time/gpu_time)

2.7162892818450928
0.07480430603027344
36.311937453785156


 ## Reshape Function

In [130]:
# reshape

In [131]:
#flatten

In [139]:
i.permute(1,0)

tensor([[0.3186, 0.9905, 0.6148, 0.0042, 0.6030, 0.0281, 0.3647, 0.3196, 0.8300,
         0.5118],
        [0.6480, 0.4364, 0.6595, 0.1301, 0.5292, 0.5881, 0.4997, 0.1148, 0.7043,
         0.1915],
        [0.0896, 0.2021, 0.6404, 0.0285, 0.1678, 0.1775, 0.4781, 0.5723, 0.3365,
         0.0202],
        [0.6143, 0.5753, 0.7487, 0.6652, 0.3133, 0.8234, 0.2818, 0.4967, 0.2523,
         0.4407],
        [0.8915, 0.4452, 0.2047, 0.4209, 0.1680, 0.9582, 0.4677, 0.9201, 0.7880,
         0.8791],
        [0.9506, 0.7684, 0.4303, 0.3953, 0.2362, 0.1134, 0.2420, 0.7533, 0.0184,
         0.1150],
        [0.1050, 0.0118, 0.1577, 0.5955, 0.6739, 0.0897, 0.7875, 0.5857, 0.0932,
         0.8012],
        [0.1112, 0.1458, 0.0268, 0.2224, 0.6119, 0.2174, 0.7843, 0.9993, 0.5202,
         0.3497],
        [0.6743, 0.5906, 0.3150, 0.3663, 0.4848, 0.2125, 0.7740, 0.9942, 0.3756,
         0.4674],
        [0.6665, 0.3770, 0.8701, 0.6285, 0.3609, 0.3243, 0.6381, 0.6669, 0.2580,
         0.3692]], device='c

In [134]:
i

tensor([[0.3186, 0.6480, 0.0896, 0.6143, 0.8915, 0.9506, 0.1050, 0.1112, 0.6743,
         0.6665],
        [0.9905, 0.4364, 0.2021, 0.5753, 0.4452, 0.7684, 0.0118, 0.1458, 0.5906,
         0.3770],
        [0.6148, 0.6595, 0.6404, 0.7487, 0.2047, 0.4303, 0.1577, 0.0268, 0.3150,
         0.8701],
        [0.0042, 0.1301, 0.0285, 0.6652, 0.4209, 0.3953, 0.5955, 0.2224, 0.3663,
         0.6285],
        [0.6030, 0.5292, 0.1678, 0.3133, 0.1680, 0.2362, 0.6739, 0.6119, 0.4848,
         0.3609],
        [0.0281, 0.5881, 0.1775, 0.8234, 0.9582, 0.1134, 0.0897, 0.2174, 0.2125,
         0.3243],
        [0.3647, 0.4997, 0.4781, 0.2818, 0.4677, 0.2420, 0.7875, 0.7843, 0.7740,
         0.6381],
        [0.3196, 0.1148, 0.5723, 0.4967, 0.9201, 0.7533, 0.5857, 0.9993, 0.9942,
         0.6669],
        [0.8300, 0.7043, 0.3365, 0.2523, 0.7880, 0.0184, 0.0932, 0.5202, 0.3756,
         0.2580],
        [0.5118, 0.1915, 0.0202, 0.4407, 0.8791, 0.1150, 0.8012, 0.3497, 0.4674,
         0.3692]], device='c

In [140]:
# Unsqeeze

In [141]:
# Squeeze

## Numpy - PyTorch

In [143]:
import numpy

In [146]:
a = torch.tensor([2,3,4])
a

tensor([2, 3, 4])

In [147]:
b=a.numpy()

In [148]:
b

array([2, 3, 4])

In [151]:
type(b)

numpy.ndarray

In [152]:
torch.tensor(b)

tensor([2, 3, 4])

In [153]:
torch.from_numpy(b)

tensor([2, 3, 4])